services:
  tigerbeetle:
    image: ghcr.io/tigerbeetle/tigerbeetle:0.17.4
    container_name: cashi-tigerbeetle
    security_opt:
      - seccomp=unconfined
    command:
      - start
      - --addresses=0.0.0.0:3000
      - --development
      - /data/0_0.tigerbeetle
    ports:
      - "3000:3000"
    volumes:
      - tigerbeetle-data:/data

volumes:
  tigerbeetle-data: