ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.cashi.SerializationKt.configureSerialization
      - com.cashi.StatusPagesKt.configureStatusPages
      - com.cashi.RoutingKt.configureRouting
